# This is a basic workflow to help you get started with Actions

name: Deploy Demo

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # This step references the directory that contains the action.
      - name: Render Deploy Action         
        id: render-deploy
        uses: ./.github/actions/render-deploy-action
        with: 
          token: ${{ secrets.GH_TOKEN }}
          render-email: ${{ secrets.RENDER_EMAIL }}
          render-password: ${{ secrets.RENDER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Echo deploy
        run: |
          echo ${{ steps.render-deploy.outputs.preview-url }}
