# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # Runs a single command using the runners shell
      - name: Render Deploy
      - id: render-deploy
        with: 
          token: ${{ secrets.GH_TOKEN }}
          email: ${{ secrets.RENDER_EMAIL }}
          password: ${{ secrets.RENDER_PASSWORD }}
        uses: muhammad-usman-outlier/actions-demo@main

      # Runs a set of commands using the runners shell
      - name: Echo deploy
        run: |
          echo ${{ steps.render-deploy.outputs.preview-url }}
