# This is a basic workflow to help you get started with Actions

name: Deploy Demo

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - id: render-deploy
        uses: muhammad-usman-outlier/render-action-new@v3.2
        with: 
          token: ${{ secrets.GH_TOKEN }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

      # Runs a set of commands using the runners shell
      - name: Echo deploy
        run: |
          echo ${{ steps.render-deploy.outputs.preview-url }}
