# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sem_dispatch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:   
    - id: get-preview-url
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        platform: Netlify
    - name: send repository dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        EVENT: dispatchSEM
        ORG: muhammad-usman-outlier
        REPO: cypress-e2e
        URL: ${{steps.get-preview-url.outputs.comment_url}}
      run: |
        curl -d "{\"event_type\": \"${EVENT}\",\"preview_url\": \"${URL}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"

