# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sem_dispatch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.3
      id: waitFor200
      with:
        site_name: "aquamarine-trifle-1dcfd6"

    - name: send repository dispatch
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        EVENT: dispatchSEM
        ORG: muhammad-usman-outlier
        REPO: cypress-e2e
        PREVIEW_URL: ${{steps.waitFor200.outputs.url}}

      run: |
        curl -d "{\"event_type\": \"${EVENT}\",\"client_payload\": {\"url\": \"${PREVIEW_URL}\"}}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
