# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sem_dispatch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - id: get-preview-url1
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 0
    - id: get-preview-url2
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 1
    - id: get-preview-url3
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 2
    - id: get-preview-url4
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 3
    - id: get-preview-url5
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 4
    - id: get-preview-url6
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 5
    - id: get-preview-url7
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 6
    - id: get-preview-url8
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 7
    - id: get-preview-url9
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 8
    - id: get-preview-url10
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 9
    - id: get-preview-url11
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 10
    - id: get-preview-url12
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 11
    - id: get-preview-url14
      uses: patzick/action-get-comment-url@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        pattern: Follow its progress at
        index: 12
    - name: Log results
      run: |
        echo " 0${{ steps.get-preview-url1.outputs.comment_url }} 1${{ steps.get-preview-url2.outputs.comment_url }}
         2${{ steps.get-preview-url3.outputs.comment_url }} 3${{ steps.get-preview-url4.outputs.comment_url }}
          4${{ steps.get-preview-url5.outputs.comment_url }} 5${{ steps.get-preview-url6.outputs.comment_url }}
           6${{ steps.get-preview-url7.outputs.comment_url }} 7${{ steps.get-preview-url8.outputs.comment_url }}
            8${{ steps.get-preview-url9.outputs.comment_url }} 9${{ steps.get-preview-url10.outputs.comment_url }}
             10${{ steps.get-preview-url11.outputs.comment_url }} 11${{ steps.get-preview-url12.outputs.comment_url }}
              12${{ steps.get-preview-url13.outputs.comment_url }} 13${{ steps.get-preview-url14.outputs.comment_url }}"
#     - name: Waiting for 200 from the Netlify Preview
#       uses: jakepartusch/wait-for-netlify-action@v1.3
#       id: waitFor200
#       with:
#         site_name: "aquamarine-trifle-1dcfd6"
# 
#     - name: send repository dispatch
#       env:
#         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         EVENT: dispatchSEM
#         ORG: muhammad-usman-outlier
#         REPO: cypress-e2e
#         PREVIEW_URL: ${{steps.waitFor200.outputs.url}}

#       run: |
#         curl -d "{\"event_type\": \"${EVENT}\",\"client_payload\": {\"url\": \"${PREVIEW_URL}\"}}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
